services:

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15673:15672"
  main:
    build:
      context: ./main
      args:
        - NODE_ENV=development
    ports:
      - "3003:3003"
    volumes:
      - ./main:/app/
    environment:
      - SERVICE=main
    depends_on:
      - postgresql
      - rabbitmq

volumes:
  data:

